### PR TITLE
fix: remove unnecessary double quotes

### LINKED ISSUE #230: AutoML: docstring typo in TablesClient
#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-automl` version: 2.4.2

#### Code example

```python
raise ValueError(
    "One of 'gcs_input_uris'/'bigquery_input_uris' must" "be set"
)
```

* https://github.com/googleapis/python-automl/blob/master/google/cloud/automl_v1beta1/services/tables/tables_client.py#L289
* https://github.com/googleapis/python-automl/blob/master/google/cloud/automl_v1beta1/services/tables/tables_client.py#L366
* https://github.com/googleapis/python-automl/blob/master/google/cloud/automl_v1beta1/services/tables/tables_client.py#L600
* https://github.com/googleapis/python-automl/blob/master/google/cloud/automl_v1beta1/services/tables/tables_client.py#L2580
* https://github.com/googleapis/python-automl/blob/master/google/cloud/automl_v1beta1/services/tables/tables_client.py#L2984

### PR DESCRIPTION
**Pull request by santiagotoscanini**
fix: remove unnecessary double quotes

Remove unnecessary double quotes (i.e: "...must" "be set...")

in `google/cloud/automl_v1beta1/services/tables/tables_client.py`

Fixes #230 🦕

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]

**Comment by busunkim96** [comment]
Thank you for the patch @santiagotoscanini!

**Comment by tseaver** [comment]
@busunkim96 Is `google/cloud/automl_v1beta1/services/tables/tables_client.py` not generated?

**Comment by santiagotoscanini** [comment]
> @busunkim96 Is `google/cloud/automl_v1beta1/services/tables/tables_client.py` not generated?

Does the CI fail because of the `black` linter error on  `google/cloud/automl_v1beta1/services/tables/tables_client.py`?

**Comment by tseaver** [comment]
@santiagotoscanini Yes, it does.  Can you run `nox -s blacken` in your local clone, and then commit and push the updated file to this PR?

**Comment by santiagotoscanini** [comment]
@tseaver I pushed the file, but the CI seems to be stuck (~3 hours)

**Comment by dandhlee** [comment]
```py
@pytest.fixture(scope="function")
    def operation_id():
        client = automl.AutoMlClient()
        project_location = f"projects/{PROJECT_ID}/locations/us-central1"

        generator = client._transport.operations_client.list_operations(
            project_location, filter_=""
        ).pages
        page = next(generator)
>       operation = page.next()
E       AttributeError: 'Page' object has no attribute 'next'

get_operation_status_test.py:34: AttributeError
```
Looks unrelated to this change, has there been a breaking change that came in recently? Or did this flake?

**Comment by tseaver** [comment]
@dandhlee the Flakybot logged new issues for this failure today:

- https://github.com/googleapis/python-automl/issues/231
- https://github.com/googleapis/python-automl/issues/232

**Pull request closed without merging**
